version: "3.8"

services:
  database:
    image: "postgres:14.2-bullseye"
    ports:
      - "5432:5432"
    volumes:
      - "{{cookiecutter.project_name}}_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: {{cookiecutter.project_name}}
      POSTGRES_USER: {{cookiecutter.project_name}}
      POSTGRES_PASSWORD: postgres

volumes:
  {{cookiecutter.project_name}}_data:
